### ISSUE TITLE
Logs, Metrics, Tracing

### ISSUE THREAD

**Issue by IfSentient** [grafana/grafana-app-sdk#24]
An issue of two parts:
1. The library code (all packages that aren't `cmd/*` and `codegen`) should have hooks for accepting interfaces for loggers, metrics, and tracing. It should be simple for a user of the SDK to get logs or metrics from underlying systems, such as the kubernetes client, informers, or OpinionatedWatchers.
2. The boilerplate code generated with `grafana-app-sdk project component add` should include pre-built solutions for logging, metrics, and traces.
```[tasklist]
### Tasks
- [x] Add Tracing Instrumentation to the SDK (https://github.com/grafana/grafana-app-sdk/pull/75)
- [x] Add Logging Instrumentation to the SDK (https://github.com/grafana/grafana-app-sdk/pull/89)
- [x] Add Metric instrumentation to the SDK (https://github.com/grafana/grafana-app-sdk/pull/103)
- [ ] Update Docs
```

**Comment by ellisda** [comment]
FWIW, the SLO app was interested in metrics for our telemetry (i.e. counter metrics of how many times our users CRUD their SLOs). see https://github.com/grafana/product_analytics/issues/54. If our api/controller weren't running inside the hosted-grafana pod, we could emit our own metrics but we don't have away to get our metrics scraped at present.

When we start running a multitenant controller, outside of hosted-grafana pod, we'll be able to emit the metrics ourselves, but we had wondered if there was some piece of infrastructure in the CRD api server that might be able to expose these kinds of counters for us (and for other kinds, rather than have each kind's controller do it from scratch).

I'm not sure this request is in-scope for your issue #24 here, but thought I'd elaborate.

**Comment by radiohead** [comment]
Marking this as closed since the SDK has been instrumented.
